version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: kornelia
      POSTGRES_PASSWORD: warcaby
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
